[ejs.app]
title = "Oasis SMP"

[ejs.landing]
mediaGitHubURL = "#"
mediaXURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://go.hrkt.org/mc/discord"

[ejs.settings]
sourceGithubLink = "#"
supportLink = "https://go.hrkt.org/mc/discord"

[ejs.welcome]
welcomeHeader = "WELCOME TO OASIS SMP"
welcomeDescription = "Mod導入で新しい世界へ！NeoForge 1.21.1 で動作するマルチサーバーです。Java や Mod のインストールは自動で行われます。"
welcomeDescCTA = "あと少しでサーバーに参加できます！"
continueButton = "続ける"
